	mysystem u0 (
		.alt_vip_itc_0_clocked_video_vid_clk       (<connected-to-alt_vip_itc_0_clocked_video_vid_clk>),       //  alt_vip_itc_0_clocked_video.vid_clk
		.alt_vip_itc_0_clocked_video_vid_data      (<connected-to-alt_vip_itc_0_clocked_video_vid_data>),      //                             .vid_data
		.alt_vip_itc_0_clocked_video_underflow     (<connected-to-alt_vip_itc_0_clocked_video_underflow>),     //                             .underflow
		.alt_vip_itc_0_clocked_video_vid_datavalid (<connected-to-alt_vip_itc_0_clocked_video_vid_datavalid>), //                             .vid_datavalid
		.alt_vip_itc_0_clocked_video_vid_v_sync    (<connected-to-alt_vip_itc_0_clocked_video_vid_v_sync>),    //                             .vid_v_sync
		.alt_vip_itc_0_clocked_video_vid_h_sync    (<connected-to-alt_vip_itc_0_clocked_video_vid_h_sync>),    //                             .vid_h_sync
		.alt_vip_itc_0_clocked_video_vid_f         (<connected-to-alt_vip_itc_0_clocked_video_vid_f>),         //                             .vid_f
		.alt_vip_itc_0_clocked_video_vid_h         (<connected-to-alt_vip_itc_0_clocked_video_vid_h>),         //                             .vid_h
		.alt_vip_itc_0_clocked_video_vid_v         (<connected-to-alt_vip_itc_0_clocked_video_vid_v>),         //                             .vid_v
		.clk_65_clk                                (<connected-to-clk_65_clk>),                                //                       clk_65.clk
		.hps_0_h2f_reset_reset_n                   (<connected-to-hps_0_h2f_reset_reset_n>),                   //              hps_0_h2f_reset.reset_n
		.hps_io_hps_io_sdio_inst_CMD               (<connected-to-hps_io_hps_io_sdio_inst_CMD>),               //                       hps_io.hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0                (<connected-to-hps_io_hps_io_sdio_inst_D0>),                //                             .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1                (<connected-to-hps_io_hps_io_sdio_inst_D1>),                //                             .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK               (<connected-to-hps_io_hps_io_sdio_inst_CLK>),               //                             .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2                (<connected-to-hps_io_hps_io_sdio_inst_D2>),                //                             .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3                (<connected-to-hps_io_hps_io_sdio_inst_D3>),                //                             .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0                (<connected-to-hps_io_hps_io_usb1_inst_D0>),                //                             .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1                (<connected-to-hps_io_hps_io_usb1_inst_D1>),                //                             .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2                (<connected-to-hps_io_hps_io_usb1_inst_D2>),                //                             .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3                (<connected-to-hps_io_hps_io_usb1_inst_D3>),                //                             .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4                (<connected-to-hps_io_hps_io_usb1_inst_D4>),                //                             .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5                (<connected-to-hps_io_hps_io_usb1_inst_D5>),                //                             .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6                (<connected-to-hps_io_hps_io_usb1_inst_D6>),                //                             .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7                (<connected-to-hps_io_hps_io_usb1_inst_D7>),                //                             .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK               (<connected-to-hps_io_hps_io_usb1_inst_CLK>),               //                             .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP               (<connected-to-hps_io_hps_io_usb1_inst_STP>),               //                             .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR               (<connected-to-hps_io_hps_io_usb1_inst_DIR>),               //                             .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT               (<connected-to-hps_io_hps_io_usb1_inst_NXT>),               //                             .hps_io_usb1_inst_NXT
		.hps_io_hps_io_uart0_inst_RX               (<connected-to-hps_io_hps_io_uart0_inst_RX>),               //                             .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX               (<connected-to-hps_io_hps_io_uart0_inst_TX>),               //                             .hps_io_uart0_inst_TX
		.led_external_connection_export            (<connected-to-led_external_connection_export>),            //      led_external_connection.export
		.memory_mem_a                              (<connected-to-memory_mem_a>),                              //                       memory.mem_a
		.memory_mem_ba                             (<connected-to-memory_mem_ba>),                             //                             .mem_ba
		.memory_mem_ck                             (<connected-to-memory_mem_ck>),                             //                             .mem_ck
		.memory_mem_ck_n                           (<connected-to-memory_mem_ck_n>),                           //                             .mem_ck_n
		.memory_mem_cke                            (<connected-to-memory_mem_cke>),                            //                             .mem_cke
		.memory_mem_cs_n                           (<connected-to-memory_mem_cs_n>),                           //                             .mem_cs_n
		.memory_mem_ras_n                          (<connected-to-memory_mem_ras_n>),                          //                             .mem_ras_n
		.memory_mem_cas_n                          (<connected-to-memory_mem_cas_n>),                          //                             .mem_cas_n
		.memory_mem_we_n                           (<connected-to-memory_mem_we_n>),                           //                             .mem_we_n
		.memory_mem_reset_n                        (<connected-to-memory_mem_reset_n>),                        //                             .mem_reset_n
		.memory_mem_dq                             (<connected-to-memory_mem_dq>),                             //                             .mem_dq
		.memory_mem_dqs                            (<connected-to-memory_mem_dqs>),                            //                             .mem_dqs
		.memory_mem_dqs_n                          (<connected-to-memory_mem_dqs_n>),                          //                             .mem_dqs_n
		.memory_mem_odt                            (<connected-to-memory_mem_odt>),                            //                             .mem_odt
		.memory_mem_dm                             (<connected-to-memory_mem_dm>),                             //                             .mem_dm
		.memory_oct_rzqin                          (<connected-to-memory_oct_rzqin>),                          //                             .oct_rzqin
		.sdram_clk_clk                             (<connected-to-sdram_clk_clk>),                             //                    sdram_clk.clk
		.sdram_wire_addr                           (<connected-to-sdram_wire_addr>),                           //                   sdram_wire.addr
		.sdram_wire_ba                             (<connected-to-sdram_wire_ba>),                             //                             .ba
		.sdram_wire_cas_n                          (<connected-to-sdram_wire_cas_n>),                          //                             .cas_n
		.sdram_wire_cke                            (<connected-to-sdram_wire_cke>),                            //                             .cke
		.sdram_wire_cs_n                           (<connected-to-sdram_wire_cs_n>),                           //                             .cs_n
		.sdram_wire_dq                             (<connected-to-sdram_wire_dq>),                             //                             .dq
		.sdram_wire_dqm                            (<connected-to-sdram_wire_dqm>),                            //                             .dqm
		.sdram_wire_ras_n                          (<connected-to-sdram_wire_ras_n>),                          //                             .ras_n
		.sdram_wire_we_n                           (<connected-to-sdram_wire_we_n>),                           //                             .we_n
		.switches_external_connection_export       (<connected-to-switches_external_connection_export>),       // switches_external_connection.export
		.system_ref_clk_clk                        (<connected-to-system_ref_clk_clk>),                        //               system_ref_clk.clk
		.system_ref_reset_reset                    (<connected-to-system_ref_reset_reset>),                    //             system_ref_reset.reset
		.sdramstartstop_readdata                   (<connected-to-sdramstartstop_readdata>),                   //               sdramstartstop.readdata
		.sdramstartstop_beginbursttransfer         (<connected-to-sdramstartstop_beginbursttransfer>),         //                             .beginbursttransfer
		.sdramstartstop_writeresponsevalid_n       (<connected-to-sdramstartstop_writeresponsevalid_n>),       //                             .writeresponsevalid_n
		.donesig_export                            (<connected-to-donesig_export>),                            //                      donesig.export
		.startsig_export                           (<connected-to-startsig_export>)                            //                     startsig.export
	);

