# TCL File Generated by Component Editor 15.0
# Wed May 25 05:20:46 PDT 2016
# DO NOT MODIFY


# 
# sdram_master "sdram_master" v1.0
#  2016.05.25.05:20:46
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module sdram_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME sdram_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom IP"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sdram_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sdram_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sdram_master.v VERILOG PATH sdram_master.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL sdram_master
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sdram_master.v VERILOG PATH sdram_master.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end s readdata Output 4
add_interface_port conduit_end startSig beginbursttransfer Input 1
add_interface_port conduit_end doneSig writeresponsevalid_n Output 1


# 
# connection point On_Chip_Master
# 
add_interface On_Chip_Master avalon start
set_interface_property On_Chip_Master addressUnits WORDS
set_interface_property On_Chip_Master associatedClock clock
set_interface_property On_Chip_Master associatedReset reset
set_interface_property On_Chip_Master bitsPerSymbol 8
set_interface_property On_Chip_Master burstOnBurstBoundariesOnly false
set_interface_property On_Chip_Master burstcountUnits WORDS
set_interface_property On_Chip_Master doStreamReads false
set_interface_property On_Chip_Master doStreamWrites false
set_interface_property On_Chip_Master holdTime 0
set_interface_property On_Chip_Master linewrapBursts false
set_interface_property On_Chip_Master maximumPendingReadTransactions 0
set_interface_property On_Chip_Master maximumPendingWriteTransactions 0
set_interface_property On_Chip_Master readLatency 0
set_interface_property On_Chip_Master readWaitTime 0
set_interface_property On_Chip_Master setupTime 0
set_interface_property On_Chip_Master timingUnits Cycles
set_interface_property On_Chip_Master writeWaitTime 0
set_interface_property On_Chip_Master ENABLED true
set_interface_property On_Chip_Master EXPORT_OF ""
set_interface_property On_Chip_Master PORT_NAME_MAP ""
set_interface_property On_Chip_Master CMSIS_SVD_VARIABLES ""
set_interface_property On_Chip_Master SVD_ADDRESS_GROUP ""

add_interface_port On_Chip_Master readDataOnChip readdata Input 16
add_interface_port On_Chip_Master addressOnChip address Output 32
add_interface_port On_Chip_Master chipselectOnChip chipselect Output 1
add_interface_port On_Chip_Master write write Output 1
add_interface_port On_Chip_Master byteenableOnChip byteenable Output 2
add_interface_port On_Chip_Master writeDataOnChip writedata Output 16


# 
# connection point SDramMaster
# 
add_interface SDramMaster avalon start
set_interface_property SDramMaster addressUnits WORDS
set_interface_property SDramMaster associatedClock clock
set_interface_property SDramMaster associatedReset reset
set_interface_property SDramMaster bitsPerSymbol 8
set_interface_property SDramMaster burstOnBurstBoundariesOnly false
set_interface_property SDramMaster burstcountUnits WORDS
set_interface_property SDramMaster doStreamReads false
set_interface_property SDramMaster doStreamWrites false
set_interface_property SDramMaster holdTime 0
set_interface_property SDramMaster linewrapBursts false
set_interface_property SDramMaster maximumPendingReadTransactions 0
set_interface_property SDramMaster maximumPendingWriteTransactions 0
set_interface_property SDramMaster readLatency 0
set_interface_property SDramMaster readWaitTime 0
set_interface_property SDramMaster setupTime 0
set_interface_property SDramMaster timingUnits Cycles
set_interface_property SDramMaster writeWaitTime 0
set_interface_property SDramMaster ENABLED true
set_interface_property SDramMaster EXPORT_OF ""
set_interface_property SDramMaster PORT_NAME_MAP ""
set_interface_property SDramMaster CMSIS_SVD_VARIABLES ""
set_interface_property SDramMaster SVD_ADDRESS_GROUP ""

add_interface_port SDramMaster read_n read_n Output 1
add_interface_port SDramMaster write_n write_n Output 1
add_interface_port SDramMaster chipselect chipselect Output 1
add_interface_port SDramMaster waitrequest waitrequest Input 1
add_interface_port SDramMaster address address Output 32
add_interface_port SDramMaster byteenable byteenable Output 2
add_interface_port SDramMaster readdatavalid readdatavalid Input 1
add_interface_port SDramMaster readdata readdata Input 16
add_interface_port SDramMaster writedata writedata Output 16

